[package]
name = "server"
version = "0.1.0"
authors = ["tet <gmorer@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.7"
serde = "1.0.99"
dotenv = "0.14.1"
postgres = "0.16.0-rc.2"